spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
mybatis-plus:
  type-aliases-package: com.linguxe.model.entity
  mapper-locations: classpath:mappers/*.xml

